version: '2.1'

services:
  tosum:
    image: tosum
    build: ./tosum_app
    ports:
    - "4000:4000"

  score:
    image: score
    build: ./score_app
    ports:
    - "4200:4200"

  auth:
    image: auth
    build: ./auth_app
    ports:
    - "4100:4100"